#!/bin/bash

sysctl kernel.printk=6
dyndbg func raid5_make_request +p
dyndbg func reshape_request +p
dyndbg func handle_stripe +p
dyndbg func handle_stripe_expansion +p
dyndbg func analyse_stripe +p
dyndbg func ops_run_io +p
dyndbg func raid5_end_read_request +p
dyndbg func raid5_end_write_request +p

#dyndbg func make_stripe_request +p
#dyndbg func __add_stripe_bio +p
#dyndbg file raid5.c +p
