#!/usr/bin/env python3

import md
import os
import sys

if __name__ == "__main__":
    if os.geteuid() != 0:
        sys.exit("Must run as root")

    inst = md.MDInstance()
    inst.setup_from_args()
