#!/usr/bin/env python3

import md
import os
import sys

if __name__ == "__main__":

    md_parser = md.MDArgumentParser()
    args = md_parser.parse_args()
    if os.geteuid() != 0:
        sys.exit("Must run as root")

    inst = md.MDInstance.create_from_parsed_args(args)
    inst.setup()
