#!/bin/bash

set -e

function run_test()
{
	echo "  " "$@"
	"$@" > /dev/null
}

function all_tests() {
	run_test ./test1
	run_test ./test2
	run_test ./test3
	run_test ./test3_all
	if [ "$NO_RESHAPE" != "y" ]; then
		run_test ./test3 -g
	fi
	run_test ./test2
	run_test fio test1.fio
	run_test fio test2.fio
	run_test fio test_4jobs.fio
}

export ZERO_FIRST=y
export QUIET=y

echo "Default Settings"
all_tests

echo "No Force"
export FORCE=n
all_tests

echo "Bitmap"
export POLICY=bitmap
all_tests

echo "PPL"
export POLICY=ppl
export NO_RESHAPE=y
all_tests

echo "Journal"
if [ -z ${DEVICES+x} ]; then
	export JOURNAL=/dev/ram7
else
	TMP=($DEVICES)
	export JOURNAL=${TMP[7]}
fi
echo "  dev:$JOURNAL"
export NO_RESHAPE=y
export POLICY=journal
all_tests

unset NO_RESHAPE
unset JOURNAL
unset POLICY

echo "Raid6"
export DISKS=4
export LEVEL=6
all_tests
unset DISKS

echo "Raid6 Bitmap"
export DISKS=4
export LEVEL=6
export POLICY=bitmap
all_tests
unset DISKS
unset POLICY

echo "Raid4"
export LEVEL=4
all_tests
unset LEVEL
